"use client";

import { useEffect, useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/context/auth-context";
import { fetchTransactions, fetchStatements } from "@/lib/storage";
import {
  calculateFinancialSummary,
  calculateCategorySpending,
  calculateTopMerchants,
  detectPotentiallyReducibleSpending,
  detectRecurringPayments,
} from "@/lib/analytics";
import { Statement, Transaction } from "@/types";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import {
  FileText,
  Printer,
  ArrowLeft,
  Sparkles,
  ShieldCheck,
  Calendar,
  CheckCircle,
} from "lucide-react";

export default function ReportPage() {
  const router = useRouter();
  const { user, loading: authLoading } = useAuth();
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [statements, setStatements] = useState<Statement[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading && !user) {
      router.push("/login");
      return;
    }

    async function loadData() {
      if (!user) return;
      setLoading(true);
      const txs = await fetchTransactions(user.id);
      const stmts = await fetchStatements(user.id);
      setTransactions(txs);
      setStatements(stmts);
      setLoading(false);
    }

    if (user) {
      loadData();
    }
  }, [user, authLoading, router]);

  const summary = useMemo(() => calculateFinancialSummary(transactions), [transactions]);
  const categories = useMemo(() => calculateCategorySpending(transactions), [transactions]);
  const topMerchants = useMemo(() => calculateTopMerchants(transactions, 6), [transactions]);
  const reducible = useMemo(() => detectPotentiallyReducibleSpending(transactions), [transactions]);
  const recurring = useMemo(() => detectRecurringPayments(transactions), [transactions]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#080B13] text-slate-100 print:bg-white print:text-black">
      <div className="print:hidden">
        <Navbar />
      </div>

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 print:hidden">
          <div>
            <Link
              href="/dashboard"
              className="text-xs font-medium text-slate-400 hover:text-white inline-flex items-center gap-1.5 mb-2 transition-colors"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Back to Command Center</span>
            </Link>
            <h1 className="text-2xl font-bold tracking-tight text-white">
              Executive Monthly Financial Report
            </h1>
            <p className="text-xs text-slate-400 mt-1">
              Consolidated, printable statement review generated by SpendWise AI.
            </p>
          </div>

          <button
            onClick={handlePrint}
            disabled={!transactions.length}
            className="px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs flex items-center gap-2 shadow-lg shadow-emerald-500/20 transition-all cursor-pointer self-start sm:self-auto"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Export PDF</span>
          </button>
        </div>

        {transactions.length === 0 ? (
          <div className="glass-panel rounded-3xl p-12 text-center text-slate-500 max-w-lg mx-auto print:hidden">
            <p className="text-xs mb-3">No statements uploaded to generate report.</p>
            <Link
              href="/upload"
              className="px-4 py-2 rounded-xl bg-emerald-500 text-slate-950 font-bold text-xs inline-block"
            >
              Upload Statement →
            </Link>
          </div>
        ) : (
          /* Formal Report Container */
          <div className="bg-[#0C101C] print:bg-white print:text-black border border-[#1E2638] print:border-gray-300 rounded-3xl p-6 sm:p-10 space-y-8 shadow-xl">
            {/* Report Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 border-b border-slate-800 print:border-gray-300 gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-lg bg-emerald-500 flex items-center justify-center text-black font-bold text-sm">
                    SW
                  </div>
                  <span className="text-xl font-bold tracking-tight text-white print:text-black">
                    SpendWise AI
                  </span>
                </div>
                <div className="text-xs text-slate-400 print:text-gray-600 mt-1">
                  Personal Financial Detective Report
                </div>
              </div>

              <div className="text-right sm:text-right text-xs text-slate-400 print:text-gray-600 space-y-0.5">
                <div>
                  <strong className="text-white print:text-black">Account:</strong> {user?.name || "Member"}
                </div>
                <div>
                  <strong className="text-white print:text-black">Period:</strong> {summary.periodStart} to {summary.periodEnd}
                </div>
                <div>
                  <strong className="text-white print:text-black">Generated:</strong> {new Date().toLocaleDateString("en-IN")}
                </div>
              </div>
            </div>

            {/* Core Snapshot Numbers */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-2xl bg-slate-900/60 print:bg-gray-100 border border-slate-800 print:border-gray-200">
              <div>
                <div className="text-[10px] uppercase tracking-wider text-slate-400 print:text-gray-500">
                  Total Income
                </div>
                <div className="text-xl font-bold text-white print:text-black mt-0.5">
                  ₹{summary.totalIncome.toLocaleString("en-IN")}
                </div>
              </div>

              <div>
                <div className="text-[10px] uppercase tracking-wider text-slate-400 print:text-gray-500">
                  Total Outflows
                </div>
                <div className="text-xl font-bold text-rose-400 print:text-rose-700 mt-0.5">
                  ₹{summary.totalExpenses.toLocaleString("en-IN")}
                </div>
              </div>

              <div>
                <div className="text-[10px] uppercase tracking-wider text-slate-400 print:text-gray-500">
                  Net Retained
                </div>
                <div className="text-xl font-bold text-emerald-400 print:text-emerald-700 mt-0.5">
                  {summary.netCashFlow >= 0 ? "+" : ""}₹{summary.netCashFlow.toLocaleString("en-IN")}
                </div>
              </div>

              <div>
                <div className="text-[10px] uppercase tracking-wider text-slate-400 print:text-gray-500">
                  Volume
                </div>
                <div className="text-xl font-bold text-white print:text-black mt-0.5">
                  {summary.transactionCount} transactions
                </div>
              </div>
            </div>

            {/* AI Executive Observations */}
            <div className="p-4 rounded-2xl bg-emerald-500/10 print:bg-emerald-50 border border-emerald-500/20 print:border-emerald-200 space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 print:text-emerald-800">
                <Sparkles className="w-4 h-4" />
                <span>SpendWise AI Executive Observations</span>
              </div>
              <p className="text-xs text-slate-300 print:text-gray-800 leading-relaxed">
                During this period, you retained a net of ₹{summary.netCashFlow.toLocaleString("en-IN")}. Your largest single expenditure was in{" "}
                <strong>{summary.largestCategory?.category || "Unknown"}</strong>, totaling ₹
                {summary.largestCategory?.amount.toLocaleString("en-IN")} (
                {summary.largestCategory?.percentage.toFixed(0)}% of total outflows). We identified{" "}
                {recurring.length} recurring subscription commitments and{" "}
                {reducible.length} discretionary spending patterns you may wish to review.
              </p>
            </div>

            {/* Category Breakdown Table */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white print:text-black tracking-wide">
                Category Spending Breakdown
              </h3>
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-800 print:border-gray-300 text-[10px] uppercase text-slate-400 print:text-gray-500">
                    <th className="py-2">Category</th>
                    <th className="py-2 text-right">Count</th>
                    <th className="py-2 text-right">Share</th>
                    <th className="py-2 text-right">Total Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 print:divide-gray-200">
                  {categories.map((c) => (
                    <tr key={c.category}>
                      <td className="py-2 font-medium text-slate-200 print:text-gray-800">{c.category}</td>
                      <td className="py-2 text-right font-mono text-slate-400 print:text-gray-600">{c.count}</td>
                      <td className="py-2 text-right font-mono text-slate-400 print:text-gray-600">{c.percentage}%</td>
                      <td className="py-2 text-right font-mono font-bold text-white print:text-black">
                        ₹{c.totalAmount.toLocaleString("en-IN")}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Top 6 Merchants */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white print:text-black tracking-wide">
                Top Outflow Destinations (Merchants)
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                {topMerchants.map((m) => (
                  <div
                    key={m.merchant}
                    className="p-3 rounded-xl bg-slate-900/40 print:bg-gray-50 border border-slate-800 print:border-gray-200 flex items-center justify-between"
                  >
                    <div>
                      <div className="font-semibold text-white print:text-black">{m.merchant}</div>
                      <div className="text-[10px] text-slate-400 print:text-gray-500">
                        {m.category} • {m.count} txn(s)
                      </div>
                    </div>
                    <div className="font-mono font-bold text-white print:text-black">
                      ₹{m.totalAmount.toLocaleString("en-IN")}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Recurring Subscriptions Summary */}
            {recurring.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white print:text-black tracking-wide">
                  Active Recurring Commitments
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                  {recurring.map((r, i) => (
                    <div
                      key={i}
                      className="p-3 rounded-xl bg-slate-900/40 print:bg-gray-50 border border-slate-800 print:border-gray-200 space-y-1"
                    >
                      <div className="font-semibold text-white print:text-black">{r.merchant}</div>
                      <div className="text-emerald-400 print:text-emerald-700 font-mono font-bold">
                        ₹{r.estimatedMonthlyCost.toLocaleString("en-IN")}/mo
                      </div>
                      <div className="text-[10px] text-slate-400 print:text-gray-500">
                        {r.frequency} • {r.isCertain ? "Known" : "Possible"}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Report Footer / Disclaimers */}
            <div className="pt-6 border-t border-slate-800 print:border-gray-300 text-[10px] text-slate-500 print:text-gray-600 space-y-1">
              <p>
                <strong>Disclaimer:</strong> This report is algorithmically compiled by SpendWise AI from user-provided electronic statements. It is intended solely for personal informational tracking and does not constitute certified accounting, auditing, or tax advice.
              </p>
              <p>© SpendWise AI • Built for Indian UPI & Banking</p>
            </div>
          </div>
        )}
      </main>

      <div className="print:hidden">
        <Footer />
      </div>
    </div>
  );
}
